<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOYvE10R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOYvE10R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOYvE10R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOYvE10R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOYvE10R\App_KernelDevDebugContainer([
    'container.build_hash' => 'OYvE10R',
    'container.build_id' => '6ead8816',
    'container.build_time' => 1715697876,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOYvE10R');
